services:
  bun:
    image: docker.io/oven/bun:alpine
    working_dir: /app/laravel-example
    ports: 
      - "5173:5173"
    volumes:
      - ./laravel-example:/app/laravel-example
    command: sh -c "bunx --bun vite" 

  roadrunner:
    build:
      context: ./dockerfiles
      dockerfile: alpine.dockerfile
    ports:
      - "9807:9807"
    volumes:
      - ./laravel-example:/app/laravel-example

